<a href="https://colab.research.google.com/github/faraday08144/Ablaj-Homes/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from numpy import random
x = random.randint(100)
print(x)

14


In [10]:
x1 =random.randint(100, size=(3,3,3))
print(x1)

[[[50 46 24]
  [43 27 70]
  [13 47 35]]

 [[36 37  6]
  [33 96 13]
  [17 23 70]]

 [[41 56 22]
  [ 0 20 85]
  [43 32 88]]]


In [16]:
x2 = random.choice([3,5,7,9], p = [0.1,0.3,0.5,0.1], size=(100))
print(x2)

[9 7 7 7 7 5 7 7 3 5 7 7 7 5 7 5 7 9 7 9 7 3 7 5 5 7 7 9 5 5 3 3 5 7 7 7 5
 3 7 7 7 7 7 7 7 7 7 7 7 7 7 7 5 7 5 5 9 7 5 5 7 5 7 5 9 7 7 7 3 3 9 7 7 7
 7 7 7 5 5 5 7 7 5 7 5 7 5 7 7 3 9 9 7 5 5 7 7 7 7 5]


In [18]:
x3 = random.randint(20, size=(2,3,2))
 #print(x3)
print(random.permutation(x3))

[[[ 4 13]
  [19  9]
  [ 3  8]]

 [[ 7 18]
  [ 8 18]
  [ 3 15]]]
